// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zlkehgmovzvqcssszyck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpsa2VoZ21vdnp2cWNzc3N6eWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MDMwNzYsImV4cCI6MjA2ODM3OTA3Nn0.fkwWIKP-ZdPgc3ExSO2HbWz7qraonjc2hasBeT1_Jj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});